/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "inverter.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(InvHeader, InvHeader, AUTO)


PB_BIND(InvMotorParamCommon, InvMotorParamCommon, AUTO)


PB_BIND(InvMotorParamSine, InvMotorParamSine, AUTO)


PB_BIND(InvMotorParamFOC, InvMotorParamFOC, AUTO)


PB_BIND(InvInverterParamCommon, InvInverterParamCommon, AUTO)


PB_BIND(InvInverterParamFOC, InvInverterParamFOC, AUTO)


PB_BIND(InvDerateParamCommon, InvDerateParamCommon, AUTO)


PB_BIND(InvDerateParamSine, InvDerateParamSine, AUTO)


PB_BIND(InvChargingParam, InvChargingParam, AUTO)


PB_BIND(InvThrottleParamCommon, InvThrottleParamCommon, AUTO)


PB_BIND(InvThrottleParamSine, InvThrottleParamSine, AUTO)


PB_BIND(InvThrottleParamFOC, InvThrottleParamFOC, AUTO)


PB_BIND(InvRegenParam, InvRegenParam, AUTO)


PB_BIND(InvAutConPwmParamCommon, InvAutConPwmParamCommon, AUTO)


PB_BIND(InvConfigParams, InvConfigParams, 2)


PB_BIND(InvTelemBlockOne, InvTelemBlockOne, AUTO)


PB_BIND(InvTelemBlockTwo, InvTelemBlockTwo, AUTO)


PB_BIND(InvTelemSine, InvTelemSine, AUTO)


PB_BIND(InvTelemFOC, InvTelemFOC, AUTO)


PB_BIND(InvTelemParams, InvTelemParams, 2)


PB_BIND(InvConfig, InvConfig, 2)


PB_BIND(InvTelem, InvTelem, 2)


























